algoritmo "Ex_Soma"

// Linguagem : [PORTUGOL]
//Autor : Wellington Vaz Xavier
//Data : 09/05/2022
//Seção de Declarações

Var
   //Aqui estou declarando minhas variaveis.
   A, B: inteiro

inicio
   //Seção de comandos

   escreval("Digite o primeiro valor: ") //aqui escrevera o resultado da minha operacao na tela.
   leia(A)
   escreva("Digite o segundo valor: ")
   leia(B)

   escreval("Resultado: ", A + B)

fimalgoritmo