Algoritmo "Semana"

Var

  x : inteiro
  dia : caracter

Inicio

 leia(x)

   escolha x
   caso 1
     dia <- "Domingo"
   caso 2
     dia <- "Segunda-Feira"
   caso 3
     dia <- "Terça-Feira"
   caso 4
     dia <- "Quarta-Feira"
   caso 5
     dia <- "Quinta-Feira"
   caso 6
     dia <- "Sexta-Feira"
   caso 7
     dia <- "Sábado"
   outrocaso
     dia <- "Dia invalido"
   fimescolha
   
   escreval("Dia da semana: ", dia)
     
 

Fimalgoritmo