algoritmo "Ex_Soma"

// Linguagem : [PORTUGOL]
//Autor : Wellington Vaz Xavier
//Data : 09/05/2022
//Seção de Declarações

Var
//Aqui estou declarando minhas variaveis.
A: inteiro
B: real
C: caractere
D: logico

inicio
//Seção de comandos

A <- 10 //aqui estou declarando que o valor da varial A é 10.
B <- 2.5 // aqui estou declarando que o valor da varial B é 2.5.

escreval("RESULTADO: ", A + B) //aqui escrevera o resultado da minha operacao na tela.



fimalgoritmo
